Week6
GregoryLi0/PandaGL pull request #17
Opened 2021-08-07 07:32 UTC by GregoryLi0

1. 整理调研报告文档与需求分析报告文档
2. 添加代码规范性说明
3. 添加导出png格式图片模块
4. 使项目生成静态链接库
5. 按照规范化说明重整代码

2021-08-07 07:51 UTC, lc-soft commented
上周的修改建议完成情况：

- [x] 改用 markdown 编写 API 设计文档
- [x] 改用 markdown 编写调研报告文档
- [x] 改用 markdown 编写需求分析报告文档
- [ ] graphics_classes.md 的内容可以作为注释写到头文件中
- [ ] color/constructors.md 的内容可以作为注释写到头文件中
- [ ] 头文件都移动到 include/PandaGL 目录里
- [x] 头文件设计问题：我想看头文件提供哪些数据类型和函数还得把函数实现代码全部看一遍，阅读成本很高，按照常规写法，你应该在头文件中写内联函数代码和函数声明，函数实体代码写到 cpp 文件里。
- [x] 命名问题：函数名怎么用的小写下划线风格？选一个常见的 C++ 编码风格吧，例如 Google 的 C++ 风格指南：https://zh-google-styleguide.readthedocs.io/en/latest/google-cpp-styleguide/contents/
- [ ] include/types.h：
  - [x] Pos：获取 line_pos 的 x 还得调用 getX() 函数？直接用 line_pos.x 不更简单吗？
  - [ ] Color: 获取一个通道的色值要调用函数然后进行与运算和位移，我感觉这性能相比 color.alpha 要低。
  - [ ] Rect: 构造函数的代码过于密集，阅读成本太高了。
  - [x] 用 get/set 函数包装成员变量的读写操作有什么好处？是否过度设计了？
  - [ ] src/main.c：这个测试程序的代码应该放到 test/ 目录下。

2021-08-07 08:11 UTC, lc-soft requested changes

2021-08-07 08:11 UTC, lc-soft commented on draw.h
> +	void DrawLine(Color* buffer, Line line, int width, int height);
建议使用 Doxygen 风格的注释，可参考：

https://cloud.tencent.com/developer/news/601818

2021-08-07 08:11 UTC, lc-soft commented on draw.h
> +	void Draw(Image* res, Canvas canvas);
看不懂这注释，是把 Image 绘制到 Canvas 上？

2021-08-07 08:11 UTC, lc-soft commented on draw.h
> +	void Draw(Image* res, Canvas canvas);
不给传 x y 参数控制位置吗？

2021-08-07 08:11 UTC, lc-soft commented on types.h
> +
头文件移动到 include/PandaGL/ 里面，然后再在 include 目录里新建个 PandaGL.h 头文件，用于包含 PandaGL 的所有头文件。

2021-08-07 08:11 UTC, lc-soft commented on src/main.cpp
>  #include<atlimage.h>
与 PandaGL 核心功能无关的测试代码应该移动到 test/ 目录。

2021-08-07 08:11 UTC, lc-soft commented on src/draw.cpp
> +namespace pandagl
namespace 怎么用小写了

2021-08-07 08:11 UTC, lc-soft commented on src/draw.cpp
> +				cout << "i= " << i << endl;
绘制时还打印字符串，严重影响绘制性能

2021-08-07 08:11 UTC, lc-soft commented on src/draw.cpp
> +		cout << "graph size: " << graphs.size() << endl;
你应该给这些用于打印调试信息的代码加上预编译条件，仅在 debug 编译模式下生效，例如：

```c++
#ifdef _DEBUG
cout << "graph size: " << graphs.size() << endl;
#endif
```

2021-08-07 08:11 UTC, lc-soft commented on src/draw.cpp
> +		for (int i = 0; i < canvas.vertical_length; i++)
`vertical_length` `horizontal_length` 相比 `width` `height` 有哪些优点？

2021-08-07 08:11 UTC, lc-soft commented on types.h
> +#include<iostream>
include 后面应该空格

2021-08-07 08:15 UTC, lc-soft requested changes

2021-08-07 08:15 UTC, lc-soft commented on draw.h
> +	* width:���ػ�������Ŀ��
文件编码问题，建议改为 UTF-8

![image](https://user-images.githubusercontent.com/1730073/128593720-14bd57a2-c226-4aa8-9909-05ba53409110.png)

2021-08-07 08:15 UTC, lc-soft commented on doc/代码规范性说明.md
> +函数命名, 变量命名, 以及文件命名要有描述性; 少用缩写.
建议使用 clang-format 工具格式化代码，参考它的文档添加 .clang-format 配置文件即可。

2021-08-07 08:25 UTC, lc-soft requested changes

2021-08-07 08:25 UTC, lc-soft commented on src/main.cpp
> -#include<iostream>
你的代码库不应该直接包含第三方库的源码，应该改用 `vcpkg` 引入依赖库。

![image](https://user-images.githubusercontent.com/1730073/128593967-8bd2b166-a131-4d75-ab93-a747c0be39e5.png)

2021-08-07 08:25 UTC, lc-soft commented on src/main.cpp
> -#include<iostream>
建议分成两个 CMakeLists.txt 文件，分别用于编译 PandaGL 和测试程序。

2021-08-07 08:30 UTC, GregoryLi0 commented on draw.h
> +	void Draw(Image* res, Canvas canvas);
对使用者来说，绘制流程是：
1. 创建Canvas
2. 创建 Line 等对象，并配置参数
3. 将Line添加到Canvas中
4. 调用Draw(Image* res, Canvas canvas)函数。其中res为返回值，返回绘制完成的图像数据。

x y的位置参数在第二步的时候进行配置

2021-08-07 08:31 UTC, GregoryLi0 commented on src/draw.cpp
> +namespace pandagl
为了符合 Google 开源项目风格指南中的说明，我也不太理解小写的具体好处。

2021-08-07 08:37 UTC, GregoryLi0 commented on src/draw.cpp
> +		for (int i = 0; i < canvas.vertical_length; i++)
使用width和height，可以与线段类中线段的长度与宽度进行区分。

2021-08-07 08:52 UTC, lc-soft requested changes

2021-08-07 08:52 UTC, lc-soft commented on types.h
> +		int w;
我发现宽高的标识符有三种：`w h width height vertical_length horizontal_length`，统一采用一种吧。

2021-08-07 08:52 UTC, lc-soft commented on types.h
> +	class Rounded_rect :public Rect
`Rounded_rect` -> `RoundedRect`

2021-08-07 08:52 UTC, lc-soft commented on types.h
> +		void setInnerColor(Color color) { inner_color_ = color; };
将成员变量的读写操作包装成函数调用，是为了解决什么问题？

2021-08-07 08:52 UTC, lc-soft commented on types.h
> +			left_line_ = Line(); right_line_ = Line(); top_line_.color = frame_color;
都加分号了，别舍不得换行啊。

2021-08-07 08:52 UTC, lc-soft commented on types.h
> +			if (backAlpha == 0xff) { // Opaque background case
对一个像素点进行 alpha 混合要调用这么多函数？虽然编译器优化可以将这些函数内联，但我还是比较担心性能问题。

建议写一个测试程序，创建 A B 两个 4000x4000 的画布，给 A 填充白色，然后在一个 1000 次循环里给 B 画布填充随机透明度的纯色并混合到 A 画布上，看看耗时多长，最低要求 16 秒（60 帧/秒）以内，推荐达到 8 秒（120帧/秒）以内。

2021-08-07 09:08 UTC, GregoryLi0 commented
Rect因为这周要编写绘制代码，所以今天会重新编写Rect代码，明天上传。目前实现的alpha混合是仿照dart::ui中颜色混合方法写的，我会进行测试。如果性能不足够则改用其他方法。其他问题我会进行更改或者测试。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月7日(星期六) 下午4:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [GregoryLi0/PandaGL] Week6 (#17)





 
@lc-soft requested changes on this pull request.
 
 
In types.h:
 &gt; +			type = ClassType::ROUNDED_RECT; +		}; + +	protected: +		Oval top_left_round_; +		Oval top_right_round_; +		Oval bottom_left_round_; +		Oval bottom_right_round_; + +	}; + +	class Image +	{ +	public: +		Image() { w = 0; h = 0; }; +		int w;  
我发现宽高的标识符有三种：w h width height vertical_length horizontal_length，统一采用一种吧。
 
 
In types.h:
 &gt; +		int getFrameType() { return m_frame_type; }; + +	protected: +		float horizontal_length; +		float vertical_length; +		float frame_width_; +		Color inner_color_; +		Color frame_color_; +		Line top_line_; +		Line bottom_line_; +		Line left_line_; +		Line right_line_; +		int m_frame_type;				//FRAMETYPE +	}; + +	class Rounded_rect :public Rect  
Rounded_rect -&gt; RoundedRect
 
 
In types.h:
 &gt; +			m_frame_type = FrameType::MIDDLE; type = ClassType::RECT; +		}; +		Rect(float horizontal_length, float vertical_length, float framewidth, Color inner_color, Color frame_color, int frame_type) { +			this-&gt;horizontal_length = horizontal_length; this-&gt;vertical_length = vertical_length; frame_width_ = framewidth; +			inner_color_ = inner_color; frame_color_ = frame_color; top_line_ = Line(); bottom_line_ = Line(); +			left_line_ = Line(); right_line_ = Line(); top_line_.color = frame_color; +			bottom_line_.color = frame_color; left_line_.color = frame_color; right_line_.color = frame_color; +			m_frame_type = frame_type; type = ClassType::RECT; +		}; + +		/*sets and gets*/ +		void setHorizontalLength(float horizontal_length) { horizontal_length = horizontal_length; }; +		float getHorizontalLength() { return horizontal_length; }; +		void setVerticalLength(float vertical_length) { vertical_length = vertical_length; }; +		float getVerticalLength() { return vertical_length; }; +		void setInnerColor(Color color) { inner_color_ = color; };  
将成员变量的读写操作包装成函数调用，是为了解决什么问题？
 
 
In types.h:
 &gt; +		float radius; +	}; + +	class Rect :public Graph +	{ +	public: +		/*Constructor*/ +		Rect() { +			horizontal_length = 0; vertical_length = 0; frame_width_ = 0; inner_color_ = Color(); frame_color_ = Color(); +			top_line_ = Line(); bottom_line_ = Line(); left_line_ = Line(); right_line_ = Line(); +			m_frame_type = FrameType::MIDDLE; type = ClassType::RECT; +		}; +		Rect(float horizontal_length, float vertical_length, float framewidth, Color inner_color, Color frame_color, int frame_type) { +			this-&gt;horizontal_length = horizontal_length; this-&gt;vertical_length = vertical_length; frame_width_ = framewidth; +			inner_color_ = inner_color; frame_color_ = frame_color; top_line_ = Line(); bottom_line_ = Line(); +			left_line_ = Line(); right_line_ = Line(); top_line_.color = frame_color;  
都加分号了，别舍不得换行啊。
 
 
In types.h:
 &gt; +			c.value = (((((int)(opacity * 0xff)) &amp; 0xff) << 24) | +				((r &amp; 0xff) << 16) | +				((g &amp; 0xff) << 8) | +				((b &amp; 0xff) << 0)) &amp; 0xFFFFFFFF; +			return c; +		} + +		static Color alphaBlend(Color foreground, Color background)  +		{ +			int alpha = foreground.alpha(); +			if (alpha == 0x00) { // Foreground completely transparent. +				return background; +			} +			int invAlpha = 0xff - alpha; +			int backAlpha = background.alpha(); +			if (backAlpha == 0xff) { // Opaque background case  
对一个像素点进行 alpha 混合要调用这么多函数？虽然编译器优化可以将这些函数内联，但我还是比较担心性能问题。
 
建议写一个测试程序，创建 A B 两个 4000x4000 的画布，给 A 填充白色，然后在一个 1000 次循环里给 B 画布填充随机透明度的纯色并混合到 A 画布上，看看耗时多长，最低要求 16 秒（60 帧/秒）以内，推荐达到 8 秒（120帧/秒）以内。
 
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-08-07 12:02 UTC, lc-soft requested changes

2021-08-07 12:02 UTC, lc-soft commented on types.h
> +			value = (((a & 0xff) << 24) |
这种实现方式相比 LCUI 中的 `LCUI_ARGB` 联合体定义方式有哪些优点？

```c
typedef union LCUI_ARGB8888_ {
	int32_t value;
	struct {
		uchar_t b;
		uchar_t g;
		uchar_t r;
		uchar_t a;
	};
	struct {
		uchar_t blue;
		uchar_t green;
		uchar_t red;
		uchar_t alpha;
	};
} LCUI_ARGB, LCUI_ARGB8888, LCUI_Color;

// 占用空间大小
sizeof(LCUI_Color) == 4; 

// 初始值
LCUI_Color c = {  .value = 0xffffffff };
LCUI_Color c = { .r = 255, .g = 255, .b = 255, .a = 255 };

// 取值
printf("%d\n", c.blue);

// 赋值
c.alpha = 0;
```

2021-08-07 14:12 UTC, GregoryLi0 commented on types.h
> +			value = (((a & 0xff) << 24) |
我之前没有了解过Union类型，刚才了解并测试了一下。经过初步测试，目前PandaGL中的Color实现方式与LCUI中Union实现方式在读取四个通道数值时候的时间消耗差别不大。但从初步了解来说，Union的实现方法更加直观，从表面看效率应该更高。Class方式可以在类中定义一些静态函数，函数的从属关系更加明确，方便查找。
关于颜色的存储方式，我会再进行查找测试，看Union和Class，int_32和 四个 unsigned char 的效率差别。

测试代码如下：
`       clock_t start;
	clock_t end;
	union ColorUnion color_lcui;
	color_lcui.value = 0x222222;
	Color pandagl_color;
	start = clock();
	for (int i = 0; i < 1000; i++)
	{
		unsigned char testvar;
		/*testvar=color_lcui.a;
		testvar=color_lcui.r;
		testvar=color_lcui.g;
		testvar=color_lcui.b;*/
		
		testvar = pandagl_color.alpha();
		testvar = pandagl_color.red();
		testvar = pandagl_color.green();
		testvar = pandagl_color.blue();
		Sleep(1);                   //暂停1ms，否则完成太快计时器结果为0
	}
	end = clock();
	double endtime = (double)(end - start) / CLOCKS_PER_SEC;
	cout << "Total time:" << endtime * 1000 << "ms" << endl;	//ms为单位`

2021-08-08 12:35 UTC, lc-soft commented on draw.h
> +	void Draw(Image* res, Canvas canvas);
你这函数理解成本太高了，应该在 API 设计文档里补充相关用法示例。

2021-08-08 13:04 UTC, lc-soft commented on types.h
> +			value = (((a & 0xff) << 24) |
看来有必要再次完善调研文档，补充对颜色、像素数据、图形对象等的实现方式的调研。

2021-08-08 13:20 UTC, lc-soft commented
后续的计划：

- 完善 CMakeLists.txt 配置文件。
- 完善需求分析文档。我在项目开始前的邮件沟通中有提到多渲染后端的设计、硬件加速、局部绘制等需求，但现有的文档中并未列出它们。
- 完善调研文档，补充各个图形库中的基本概念、数据结构、代码示例，每个图形库一个文档，放在`调研文档`目录内。文档内容模板如下：

    ```md
    # (图形库名称)

    （图形库的简单介绍，包括优缺点、适用场景等）

    ## 基本概念

    （介绍该图形库的 API 采用怎样一种设计风格，需要经历怎样的流程才能绘制出图形，工作原理是怎样的）

    ### 数据结构

    （介绍该库提供的常用数据结构，各个数据结构之间的关系）

    （颜色数据的定义）
    （图形对象的定义）
    ...

    ### 函数

    （列出该库提供的常用函数，并简单介绍它们的功能）

    ## 示例

    ### 绘制线段

    （代码）

    ### 绘制矩形

    （代码）

    ### 透明度混合

    （代码）

    ### 直接操作像素数据

    （代码）

    ```

- 完善 API 设计文档。文档模板如下：

    ```md
    # PandaGL 设计文档

    ## 需求

    （介绍该项目是为了解决哪些需求而设计的，相当于对之前的邮件沟通记录、需求和调研结果做个总结）

    ## 代码风格

    （介绍采用何种编码风格）

    ## 模块

    （介绍该项目主要分为哪几大模块，它们分别负责什么功能）

    ## C++ API

    （介绍提供哪些数据结构和函数，按照功能模块分组，最好能够给每组 API 提供示例调研代码）

    ## C API

    （C API 是提供给 LCUI 调用的，必须严格遵循 LCUI 3.0 开发计划中的设计规范）
    ```

2021-08-10 13:09 UTC, lc-soft requested changes

2021-08-10 13:13 UTC, GregoryLi0 commented on doc/API设计文档.md
> +	canvas_0.graphs.push_back(&canvas_1);
这个不是最新的用法设计，最新的文档中为：
```
	//定义一个位图并初始化
	Bitmap bitmap;
	bitmap.setConfig(1920,1080);
	//分配位图所占的空间
	bitmap.allocPixels()

	//创建画布，并绑定Bitmap
	Canvas canvas(bitmap);

	//新建矩形对象，并设置矩形几何信息
	Rect r(20,20,60,40);

	//设定绘制样式
	Paint paint;
	paint.setARGB(255, 255, 0, 0);

	//绘制图像，函数更改bitmap的像素值。
	canvas.drawRect(r,paint);
```

2021-08-10 13:23 UTC, GregoryLi0 commented on doc/调研文档/Skia.md
> +        canvas->clipRect(SkRect::MakeWH(256, 256));
用于裁剪画布，也就是裁剪的区域是画布的显示区域。这段代码表示的是顺序绘制了两个图形，设置Paint的BlendMode控制混色模式。没能找到skia的不同混色模式源码，只在官方文档里找到了公式。

2021-08-13 06:15 UTC, lc-soft requested changes

2021-08-13 06:15 UTC, lc-soft commented on doc/调研文档/Skia.md
> +3. 锁定一个 Canvas，并获得上一帧非 dirtyRect 的区域。
再补充调研常见的 UI 开发库是如何基于图形库实现脏矩形绘制技术吧，例如 qt、gtk、flutter。

示例：

```md
cario 是 gtk 的图形库，gtk 的脏矩形绘制技术是通过调用 cario 的 xxxxxxx 实现的。
```

2021-08-13 06:37 UTC, GregoryLi0 commented on test/test.cpp
> +	paint.frame_width = 2;
- 绘制直线时，表示直线的宽度。
- 绘制矩形、椭圆时表示边框的宽度。边框是居中计算的，也就是说边框宽度越大，矩形FILL填充范围越小。

2021-08-13 06:40 UTC, GregoryLi0 commented on test/test.cpp
> +	paint.setARGB(60, 0, 255, 255);
我不确定是否需要其他的颜色格式，以及有可能的颜色转换等。并且setARGB能更清晰地表明四个通道的顺序，因为在一些库里会有RGBA的顺序。
我会添加paint.setColor(Color_32 color ) 函数。

2021-08-13 06:42 UTC, GregoryLi0 commented on test/test.cpp
> +	device.bitmap = &bitmap;
参考了skia的设计。skia中device不与bitmap绑定。而是canvas与bitmap或者device绑定，用于说明canvas绘制时输出到什么设备。
skia这部分具体的设计思路我还在查阅源码。

2021-08-13 06:45 UTC, GregoryLi0 commented on doc/API设计文档.md
> +Bitmap是一个二维数组，负责管理像素点阵数据。并带有Bitmap的基本信息。
代码实现是一个一维数组，我会在文档里做修改与注释。

2021-08-13 06:45 UTC, lc-soft commented on test/test.cpp
> +	paint.frame_width = 2;
看到 frame 就会想到 帧-> 一帧画面 -> 有宽高的画面，然后就会误认为 frame_width 的含义与 rect_width 相似。

建议命名为 line_width，理由：[CanvasRenderingContext2D.lineWidth
](https://developer.mozilla.org/zh-CN/docs/Web/API/CanvasRenderingContext2D/lineWidth)

2021-08-13 06:54 UTC, GregoryLi0 commented on doc/API设计文档.md
> +	Canvas canvas(bitmap);
绘制的调用过程是canvas.drawxxx()->device.drawxxx()，不同的device需要实现basedevice这个虚类，实现device中的drawxxx()函数。我认为在device的函数里操作device中的bitmap更合理些。
对于拓展性，使用者需要实现不同的device，比如MyDevice。如果使用者想使用自定义的bitmap，比如新建一个继承bitmap的MyBitmap，可以直接将MyDevice中的bitmap指针 对准MyBitmap对象。我认为这对拓展来说更有利。

2021-08-13 07:02 UTC, GregoryLi0 commented on doc/API设计文档.md
> +	canvas.drawRect(r,paint);
我之前对局部绘制的理解是绘制半个圆、半个矩形等，以为只是对图像剪裁。没有向并行绘制的方向考虑。
我现在的想法是局部绘制的作用是实现并行绘制。比如把一个矩形分成四个小矩形进行绘制，不知道理解是否有偏差？
我对这方面还没有研究，比如要用什么方法进行分块，需要动态设置分多少块等。

2021-08-13 07:02 UTC, GregoryLi0 commented on doc/调研文档/Skia.md
> +3. 锁定一个 Canvas，并获得上一帧非 dirtyRect 的区域。
收到

2021-08-13 07:06 UTC, lc-soft commented on doc/API设计文档.md
> +	Canvas canvas(bitmap);
skia 调研文档里有说指令层、解析层、渲染层，看到你说的`canvas.drawxxx()->device.drawxxx()`，这个 Device 像是指令层的实现，而不是渲染层的实现。

2021-08-13 07:07 UTC, lc-soft commented on doc/API设计文档.md
> +	canvas.drawRect(r,paint);
局部绘制不是平均分割区域然后并行绘制，而是可自由指定任意位置和大小的区域进行绘制。

2021-08-13 07:15 UTC, GregoryLi0 commented on doc/API设计文档.md
> +	Canvas canvas(bitmap);
是的，目前还没有研究到具体某个device中绘制的方法

2021-08-16 14:11 UTC, lc-soft requested changes

2021-08-16 14:11 UTC, lc-soft commented on include/PandaGL/draw/Color_32.h
> +		static Color_32 AlphaBlend(Color_32 foreground, Color_32 background)
如果用户的多个 .cpp 源文件和 .h 头文件都 `#include` 了你的头文件，在编译这些文件时是否会出现问题？

2021-08-16 14:11 UTC, lc-soft commented on include/PandaGL/types.h
> +using namespace std;
头文件不应该 `using namespace` 任何命名空间，这会污染用户代码的命名空间。

2021-08-16 14:11 UTC, lc-soft commented on include/PandaGL/types.h
> +using namespace std;
这些别人已经踩过无数遍的坑就别浪费时间再踩一遍了，找个 C++ 代码质量检查工具用一下吧，cpplint 什么的，vscode 编辑器也有相关扩展插件。

2021-08-16 14:11 UTC, lc-soft commented on include/include.h
> +#include "PandaGL/draw/Canvas.h"
你这 include.h 还没改成 PandaGL.h ？

2021-08-16 14:11 UTC, lc-soft commented on include/include.h
> +#endif // !PANDAGL_INCLUDE_H
不应该包含第三方库的头文件。测试程序要用那就在测试程序的代码里 include 它。

2021-08-16 14:32 UTC, GregoryLi0 commented on include/PandaGL/draw/Color_32.h
> +		/// @brief Constructor
我在测试的时候没有发现问题，但是在网上搜索说不能设置构造函数和静态函数。为了安全我会更改。
![Snipaste_2021-08-16_22-31-06](https://user-images.githubusercontent.com/40971816/129580406-5e452774-805f-4505-bc3d-73e197b54f04.png)

2021-08-16 14:36 UTC, GregoryLi0 commented on include/PandaGL/draw/Color_32.h
> +	union Color_32 {
经过测试是32位的
![sizeof](https://user-images.githubusercontent.com/40971816/129581121-ce21afc6-3d05-4412-a74f-ff244787a2e3.png)

2021-08-16 14:44 UTC, GregoryLi0 commented on doc/需求分析报告文档.md
> +**功能函数:** draw/line.c/Graph_DrawHorizLine & Graph_DrawVertiLine
好的  目前正在看 LCUI 的源码+写 LCUI 的调研报告，目前已经整理了大半了。

2021-08-17 00:32 UTC, GregoryLi0 commented on include/PandaGL/draw/Color_32.h
> +		/// @brief Constructor
查找的结果说，union中的变量不允许有构造函数、析构函数、拷贝函数，但对于union本身没有这个要求。对于union中能否有静态函数没有要求，有要求union中不能有静态变量。

2021-08-17 01:13 UTC, GregoryLi0 commented on doc/API设计文档.md
> +	bitmap.allocPixels()
为了给以后的拓展做准备。Bitmap除了宽高，还可能会配置更改每一个像素占用的空间，不一定是32位的。

2021-08-17 01:13 UTC, GregoryLi0 commented on doc/API设计文档.md
> +	bitmap.setConfig(1920,1080);
已更改

2021-08-17 06:22 UTC, lc-soft commented on include/PandaGL/draw/Color_32.h
> +		/// @brief Constructor
建议将 struct 和 union 只用于定义数据结构，要加构造函数和成员函数的话应该改用 class，或将它们作为 class 的成员变量。

2021-08-17 06:29 UTC, lc-soft commented on include/PandaGL/draw/Color_32.h
> +		/// @brief Constructor
可以找些与“C++ 最佳实践”相关的文章看看。

2021-08-18 07:59 UTC, lc-soft commented on doc/调研文档/LCUI.md
> +LCUI_ARGB *px_src, *px_dst;
Alpha 混合有两种处理方式：

1. 不透明的图像和透明的图像混合，包含简单的乘法、加法和位移运算，源码位置：`include/graph.h/ALPHA_BLEND`
2. 两个透明图像的混合，有较多的乘除法运算，源码位置：`include/graph.h/LCUI_OverPixel`

2021-08-18 08:22 UTC, lc-soft commented on doc/调研文档/LCUI.md
> +LCUI_Graph_ 的内部变量，用于表示与上一级的LCUI_Graph_的连接。有锁设计。
有锁？是指互斥锁，还是读写锁？

2021-08-20 14:26 UTC, lc-soft requested changes

2021-08-20 14:26 UTC, lc-soft commented on doc/API设计文档.md
> +typedef pd_line_ pd_line;
不加 `_t` 后缀标识它是个类型吗？

2021-08-20 14:41 UTC, GregoryLi0 commented on include/PandaGL/types.h
> +using namespace std;
代码已用 cpplint 检查并修改。

2021-08-20 14:53 UTC, GregoryLi0 commented on include/PandaGL/draw/Color_32.h
> +		static Color_32 AlphaBlend(Color_32 foreground, Color_32 background)
经过调查，会导致链接冲突、增加编译时间的问题。如果有static变量会产生多份实例。
但现在的C++编译器可以自动处理这些问题，会增加编译时间。
为了安全起见，应该在.cpp中进行实现。

2021-08-20 14:54 UTC, GregoryLi0 commented on include/PandaGL/draw/Color_32.h
> +		static Color_32 AlphaBlend(Color_32 foreground, Color_32 background)
经过调查，会导致链接冲突、增加编译时间的问题。如果有static变量会产生多份实例。
但现在的C++编译器可以自动处理这些问题，会增加编译时间。
为了安全起见，应该在.cpp中进行实现。

2021-08-21 01:07 UTC, GregoryLi0 commented on doc/调研文档/LCUI.md
> +LCUI_Graph_ 的内部变量，用于表示与上一级的LCUI_Graph_的连接。有锁设计。
本来以为是起到锁的作用，现在了解是标识是否有父Graph

2021-08-21 01:10 UTC, GregoryLi0 commented on doc/API设计文档.md
> +typedef pd_line_ pd_line;
感觉加了 **pd_** 前缀再添加 **_t** 后缀会显得很臃肿。比如 **pd_line_t** 您认为有必要都添加吗？

2021-08-21 01:16 UTC, lc-soft commented on doc/API设计文档.md
> +typedef pd_line_ pd_line;
加吧，类型和函数的命名应该有个区别。

2021-08-23 13:10 UTC, merged